# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
  
on:
  workflow_dispatch

jobs:
  job1:

    runs-on: ubuntu-latest  

    steps:
      - shell: bash
        run: echo "Step 1 complete!"
      - shell: bash
        run: echo "Step 2 complete!"
  job2:
      - name: Cowsays
      uses: mscoutermarsh/cowsays-action@v1
      with:
        # What does the cow say?
        text: 'Ready for prod–ship it!'
        # Color of your cow
        color: red
          
  
