# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: first workflow
  
on:
  workflow_dispatch

jobs:
  job1:

    runs-on: ubuntu-latest  

    steps:
      - shell: bash
        run: echo "Step 1 complete!"
      - shell: bash
        run: echo "Step 2 complete!"
        
  job2:
      name: Cowsays
      runs-on: ubuntu-latest
      steps:
      - name: Ship it
        uses: mscoutermarsh/cowsays-action@master
        with:
         text: 'Ready for prod–ship it!'
         color: 'red'
                 
  
          
  
